/*
 * CDR Participant Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MetaPaginated struct {
	// The total number of pages in the full set
	TotalPages int32 `json:"totalPages"`
	// The total number of records in the full set
	TotalRecords int32 `json:"totalRecords"`
}
