/*
 * CDR Participant Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Data Recipient Brand Software Products
type SoftwareProductMetaData struct {
	// Unique id of the Data Recipient software product issued by the CDR Register
	SoftwareProductId string `json:"softwareProductId"`
	// Name of the software product
	SoftwareProductName string `json:"softwareProductName"`
	// Description of the software product
	SoftwareProductDescription string `json:"softwareProductDescription,omitempty"`
	// Software product logo URI
	LogoUri string `json:"logoUri"`
	// Software Product status in the CDR Register
	Status string `json:"status"`
}
