/*
 * CDR Participant Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type DataHolderBrandSummary struct {
	// Unique id of the Data Holder Brand issued by the CDR Register
	DataHolderBrandId string `json:"dataHolderBrandId,omitempty"`
	// Interim id of the Data Holder Brand issued by the CDR Register. This is to be used to uniquely identify the record when dataHolderBrandId is not populated and is not to be reused
	InterimId string `json:"interimId,omitempty"`
	// The name of Data Holder Brand
	BrandName string `json:"brandName"`
	// Base URI for the Data Holder's Consumer Data Standard public endpoints
	PublicBaseUri string `json:"publicBaseUri"`
	// Brand logo URI
	LogoUri string `json:"logoUri"`
	// The industries the Data Holder Brand belongs to. Please note that the CDR Register entity model is constrained to one industry per brand which is planned to be relaxed in the future.
	Industries []string `json:"industries"`
	// The date/time that the Data Holder Brand data was last updated in the Register
	LastUpdated time.Time `json:"lastUpdated"`
	// Australian Business Number for the organisation
	Abn string `json:"abn,omitempty"`
	// Australian Company Number for the organisation
	Acn string `json:"acn,omitempty"`
	// Australian Registered Body Number.  ARBNs are issued to registrable Australian bodies and foreign companies
	Arbn string `json:"arbn,omitempty"`
}
