/*
 * CDR Participant Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Endpoints related to Data Holder Brand services
type RegisterDataHolderBrandServiceEndpoint struct {
	// The major version of the high level standards. This is not the version of the endpoint or the payload being requested but the version of the overall standards being applied. This version number will be \"v\" followed by the major version of the standards as a positive integer (e.g. v1, v12 or v76)
	Version string `json:"version"`
	// Base URI for the Data Holder's Consumer Data Standard public endpoints
	PublicBaseUri string `json:"publicBaseUri"`
	// Base URI for the Data Holder's Consumer Data Standard resource endpoints
	ResourceBaseUri string `json:"resourceBaseUri"`
	// Base URI for the Data Holder's Consumer Data Standard information security endpoints
	InfosecBaseUri string `json:"infosecBaseUri"`
	// Base URI for the Data Holder extension endpoints to the Consumer Data Standard (optional)
	ExtensionBaseUri string `json:"extensionBaseUri,omitempty"`
	// Publicly available website or web resource URI
	WebsiteUri string `json:"websiteUri"`
}
