/*
 * CDR Participant Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.17.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SoftwareProductStatus struct {
	// Unique id of the software product issued by the CDR Register
	SoftwareProductId string `json:"softwareProductId"`
	// Software product status in the CDR Register
	Status string `json:"status"`
}
