// Package cdrCommon provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package cdrCommon

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CommonEmailAddressPurpose.
const (
	CommonEmailAddressPurposeHOME        CommonEmailAddressPurpose = "HOME"
	CommonEmailAddressPurposeOTHER       CommonEmailAddressPurpose = "OTHER"
	CommonEmailAddressPurposeUNSPECIFIED CommonEmailAddressPurpose = "UNSPECIFIED"
	CommonEmailAddressPurposeWORK        CommonEmailAddressPurpose = "WORK"
)

// Defines values for CommonOrganisationIndustryCodeVersion.
const (
	CommonOrganisationIndustryCodeVersionANZSIC129202006V10 CommonOrganisationIndustryCodeVersion = "ANZSIC_1292.0_2006_V1.0"
	CommonOrganisationIndustryCodeVersionANZSIC129202006V20 CommonOrganisationIndustryCodeVersion = "ANZSIC_1292.0_2006_V2.0"
)

// Defines values for CommonOrganisationOrganisationType.
const (
	CommonOrganisationOrganisationTypeCOMPANY          CommonOrganisationOrganisationType = "COMPANY"
	CommonOrganisationOrganisationTypeGOVERNMENTENTITY CommonOrganisationOrganisationType = "GOVERNMENT_ENTITY"
	CommonOrganisationOrganisationTypeOTHER            CommonOrganisationOrganisationType = "OTHER"
	CommonOrganisationOrganisationTypePARTNERSHIP      CommonOrganisationOrganisationType = "PARTNERSHIP"
	CommonOrganisationOrganisationTypeSOLETRADER       CommonOrganisationOrganisationType = "SOLE_TRADER"
	CommonOrganisationOrganisationTypeTRUST            CommonOrganisationOrganisationType = "TRUST"
)

// Defines values for CommonOrganisationDetailV2IndustryCodeVersion.
const (
	CommonOrganisationDetailV2IndustryCodeVersionANZSIC129202006V10 CommonOrganisationDetailV2IndustryCodeVersion = "ANZSIC_1292.0_2006_V1.0"
	CommonOrganisationDetailV2IndustryCodeVersionANZSIC129202006V20 CommonOrganisationDetailV2IndustryCodeVersion = "ANZSIC_1292.0_2006_V2.0"
)

// Defines values for CommonOrganisationDetailV2OrganisationType.
const (
	CommonOrganisationDetailV2OrganisationTypeCOMPANY          CommonOrganisationDetailV2OrganisationType = "COMPANY"
	CommonOrganisationDetailV2OrganisationTypeGOVERNMENTENTITY CommonOrganisationDetailV2OrganisationType = "GOVERNMENT_ENTITY"
	CommonOrganisationDetailV2OrganisationTypeOTHER            CommonOrganisationDetailV2OrganisationType = "OTHER"
	CommonOrganisationDetailV2OrganisationTypePARTNERSHIP      CommonOrganisationDetailV2OrganisationType = "PARTNERSHIP"
	CommonOrganisationDetailV2OrganisationTypeSOLETRADER       CommonOrganisationDetailV2OrganisationType = "SOLE_TRADER"
	CommonOrganisationDetailV2OrganisationTypeTRUST            CommonOrganisationDetailV2OrganisationType = "TRUST"
)

// Defines values for CommonPersonOccupationCodeVersion.
const (
	CommonPersonOccupationCodeVersionANZSCO122002006V10 CommonPersonOccupationCodeVersion = "ANZSCO_1220.0_2006_V1.0"
	CommonPersonOccupationCodeVersionANZSCO122002006V11 CommonPersonOccupationCodeVersion = "ANZSCO_1220.0_2006_V1.1"
	CommonPersonOccupationCodeVersionANZSCO122002013V12 CommonPersonOccupationCodeVersion = "ANZSCO_1220.0_2013_V1.2"
	CommonPersonOccupationCodeVersionANZSCO122002013V13 CommonPersonOccupationCodeVersion = "ANZSCO_1220.0_2013_V1.3"
)

// Defines values for CommonPersonDetailV2OccupationCodeVersion.
const (
	CommonPersonDetailV2OccupationCodeVersionANZSCO122002006V10 CommonPersonDetailV2OccupationCodeVersion = "ANZSCO_1220.0_2006_V1.0"
	CommonPersonDetailV2OccupationCodeVersionANZSCO122002006V11 CommonPersonDetailV2OccupationCodeVersion = "ANZSCO_1220.0_2006_V1.1"
	CommonPersonDetailV2OccupationCodeVersionANZSCO122002013V12 CommonPersonDetailV2OccupationCodeVersion = "ANZSCO_1220.0_2013_V1.2"
	CommonPersonDetailV2OccupationCodeVersionANZSCO122002013V13 CommonPersonDetailV2OccupationCodeVersion = "ANZSCO_1220.0_2013_V1.3"
)

// Defines values for CommonPhoneNumberPurpose.
const (
	CommonPhoneNumberPurposeHOME          CommonPhoneNumberPurpose = "HOME"
	CommonPhoneNumberPurposeINTERNATIONAL CommonPhoneNumberPurpose = "INTERNATIONAL"
	CommonPhoneNumberPurposeMOBILE        CommonPhoneNumberPurpose = "MOBILE"
	CommonPhoneNumberPurposeOTHER         CommonPhoneNumberPurpose = "OTHER"
	CommonPhoneNumberPurposeUNSPECIFIED   CommonPhoneNumberPurpose = "UNSPECIFIED"
	CommonPhoneNumberPurposeWORK          CommonPhoneNumberPurpose = "WORK"
)

// Defines values for CommonPhysicalAddressAddressUType.
const (
	CommonPhysicalAddressAddressUTypePaf    CommonPhysicalAddressAddressUType = "paf"
	CommonPhysicalAddressAddressUTypeSimple CommonPhysicalAddressAddressUType = "simple"
)

// Defines values for CommonPhysicalAddressWithPurposeAddressUType.
const (
	CommonPhysicalAddressWithPurposeAddressUTypePaf    CommonPhysicalAddressWithPurposeAddressUType = "paf"
	CommonPhysicalAddressWithPurposeAddressUTypeSimple CommonPhysicalAddressWithPurposeAddressUType = "simple"
)

// Defines values for CommonPhysicalAddressWithPurposePurpose.
const (
	CommonPhysicalAddressWithPurposePurposeMAIL       CommonPhysicalAddressWithPurposePurpose = "MAIL"
	CommonPhysicalAddressWithPurposePurposeOTHER      CommonPhysicalAddressWithPurposePurpose = "OTHER"
	CommonPhysicalAddressWithPurposePurposePHYSICAL   CommonPhysicalAddressWithPurposePurpose = "PHYSICAL"
	CommonPhysicalAddressWithPurposePurposeREGISTERED CommonPhysicalAddressWithPurposePurpose = "REGISTERED"
	CommonPhysicalAddressWithPurposePurposeWORK       CommonPhysicalAddressWithPurposePurpose = "WORK"
)

// Defines values for CommonPhysicalAddressWithPurposeAllOfPurpose.
const (
	CommonPhysicalAddressWithPurposeAllOfPurposeMAIL       CommonPhysicalAddressWithPurposeAllOfPurpose = "MAIL"
	CommonPhysicalAddressWithPurposeAllOfPurposeOTHER      CommonPhysicalAddressWithPurposeAllOfPurpose = "OTHER"
	CommonPhysicalAddressWithPurposeAllOfPurposePHYSICAL   CommonPhysicalAddressWithPurposeAllOfPurpose = "PHYSICAL"
	CommonPhysicalAddressWithPurposeAllOfPurposeREGISTERED CommonPhysicalAddressWithPurposeAllOfPurpose = "REGISTERED"
	CommonPhysicalAddressWithPurposeAllOfPurposeWORK       CommonPhysicalAddressWithPurposeAllOfPurpose = "WORK"
)

// Defines values for ResponseCommonCustomerDetailV2DataCustomerUType.
const (
	ResponseCommonCustomerDetailV2DataCustomerUTypeOrganisation ResponseCommonCustomerDetailV2DataCustomerUType = "organisation"
	ResponseCommonCustomerDetailV2DataCustomerUTypePerson       ResponseCommonCustomerDetailV2DataCustomerUType = "person"
)

// Defines values for ResponseCommonCustomerDataCustomerUType.
const (
	ResponseCommonCustomerDataCustomerUTypeOrganisation ResponseCommonCustomerDataCustomerUType = "organisation"
	ResponseCommonCustomerDataCustomerUTypePerson       ResponseCommonCustomerDataCustomerUType = "person"
)

// Defines values for ResponseCommonDiscoveryStatusDataStatus.
const (
	OK              ResponseCommonDiscoveryStatusDataStatus = "OK"
	PARTIALFAILURE  ResponseCommonDiscoveryStatusDataStatus = "PARTIAL_FAILURE"
	SCHEDULEDOUTAGE ResponseCommonDiscoveryStatusDataStatus = "SCHEDULED_OUTAGE"
	UNAVAILABLE     ResponseCommonDiscoveryStatusDataStatus = "UNAVAILABLE"
)

// CommonEmailAddress defines model for CommonEmailAddress.
type CommonEmailAddress struct {
	// Address A correctly formatted email address, as defined by the addr-spec format in **[[RFC5322]](#nref-RFC5322)**
	Address string `json:"address"`

	// IsPreferred May be true for one and only one email record in the collection. Denotes the default email address
	IsPreferred *bool `json:"isPreferred,omitempty"`

	// Purpose The purpose for the email, as specified by the customer (Enumeration)
	Purpose CommonEmailAddressPurpose `json:"purpose"`
}

// CommonEmailAddressPurpose The purpose for the email, as specified by the customer (Enumeration)
type CommonEmailAddressPurpose string

// CommonOrganisation defines model for CommonOrganisation.
type CommonOrganisation struct {
	// Abn Australian Business Number for the organisation
	Abn *string `json:"abn,omitempty"`

	// Acn Australian Company Number for the organisation. Required only if an ACN is applicable for the organisation type
	Acn *string `json:"acn,omitempty"`

	// AgentFirstName The first name of the individual providing access on behalf of the organisation. For people with single names this field need not be present.  The single name should be in the lastName field
	AgentFirstName *string `json:"agentFirstName,omitempty"`

	// AgentLastName The last name of the individual providing access on behalf of the organisation. For people with single names the single name should be in this field
	AgentLastName string `json:"agentLastName"`

	// AgentRole The role of the individual identified as the agent who is providing authorisation.  Expected to be used for display. Default to Unspecified if the role is not known
	AgentRole string `json:"agentRole"`

	// BusinessName Name of the organisation
	BusinessName string `json:"businessName"`

	// EstablishmentDate The date the organisation described was established
	EstablishmentDate *string `json:"establishmentDate,omitempty"`

	// IndustryCode A valid [ANZSIC](http://www.abs.gov.au/ANZSIC) code for the organisation. If the industry code held by the data holder is not one of the supported [ANZSIC](http://www.abs.gov.au/ANZSIC) versions, then it must not be supplied.
	IndustryCode *string `json:"industryCode,omitempty"`

	// IndustryCodeVersion The applicable [ANZSIC](http://www.abs.gov.au/ANZSIC) release version of the industry code provided. Should only be supplied if ``industryCode`` is also supplied. If ``industryCode`` is supplied but ``industryCodeVersion`` is absent, default is ``ANZSIC_1292.0_2006_V2.0``
	IndustryCodeVersion *CommonOrganisationIndustryCodeVersion `json:"industryCodeVersion,omitempty"`

	// IsACNCRegistered True if registered with the ACNC.  False if not. Absent or null if not confirmed.
	IsACNCRegistered *bool `json:"isACNCRegistered,omitempty"`

	// LastUpdateTime The date and time that this record was last updated by the customer. If no update has occurred then this date should reflect the initial creation date for the data
	LastUpdateTime *string `json:"lastUpdateTime,omitempty"`

	// LegalName Legal name, if different to the business name
	LegalName *string `json:"legalName,omitempty"`

	// OrganisationType Legal organisation type
	OrganisationType CommonOrganisationOrganisationType `json:"organisationType"`

	// RegisteredCountry Enumeration with values from [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country codes.  Assumed to be AUS if absent
	RegisteredCountry *string `json:"registeredCountry,omitempty"`

	// ShortName Short name used for communication, if different to the business name
	ShortName *string `json:"shortName,omitempty"`
}

// CommonOrganisationIndustryCodeVersion The applicable [ANZSIC](http://www.abs.gov.au/ANZSIC) release version of the industry code provided. Should only be supplied if “industryCode“ is also supplied. If “industryCode“ is supplied but “industryCodeVersion“ is absent, default is “ANZSIC_1292.0_2006_V2.0“
type CommonOrganisationIndustryCodeVersion string

// CommonOrganisationOrganisationType Legal organisation type
type CommonOrganisationOrganisationType string

// CommonOrganisationDetailV2 defines model for CommonOrganisationDetailV2.
type CommonOrganisationDetailV2 struct {
	// Abn Australian Business Number for the organisation
	Abn *string `json:"abn,omitempty"`

	// Acn Australian Company Number for the organisation. Required only if an ACN is applicable for the organisation type
	Acn *string `json:"acn,omitempty"`

	// AgentFirstName The first name of the individual providing access on behalf of the organisation. For people with single names this field need not be present.  The single name should be in the lastName field
	AgentFirstName *string `json:"agentFirstName,omitempty"`

	// AgentLastName The last name of the individual providing access on behalf of the organisation. For people with single names the single name should be in this field
	AgentLastName string `json:"agentLastName"`

	// AgentRole The role of the individual identified as the agent who is providing authorisation.  Expected to be used for display. Default to Unspecified if the role is not known
	AgentRole string `json:"agentRole"`

	// BusinessName Name of the organisation
	BusinessName string `json:"businessName"`

	// EstablishmentDate The date the organisation described was established
	EstablishmentDate *string `json:"establishmentDate,omitempty"`

	// IndustryCode A valid [ANZSIC](http://www.abs.gov.au/ANZSIC) code for the organisation. If the industry code held by the data holder is not one of the supported [ANZSIC](http://www.abs.gov.au/ANZSIC) versions, then it must not be supplied.
	IndustryCode *string `json:"industryCode,omitempty"`

	// IndustryCodeVersion The applicable [ANZSIC](http://www.abs.gov.au/ANZSIC) release version of the industry code provided. Should only be supplied if ``industryCode`` is also supplied. If ``industryCode`` is supplied but ``industryCodeVersion`` is absent, default is ``ANZSIC_1292.0_2006_V2.0``
	IndustryCodeVersion *CommonOrganisationDetailV2IndustryCodeVersion `json:"industryCodeVersion,omitempty"`

	// IsACNCRegistered True if registered with the ACNC.  False if not. Absent or null if not confirmed.
	IsACNCRegistered *bool `json:"isACNCRegistered,omitempty"`

	// LastUpdateTime The date and time that this record was last updated by the customer. If no update has occurred then this date should reflect the initial creation date for the data
	LastUpdateTime *string `json:"lastUpdateTime,omitempty"`

	// LegalName Legal name, if different to the business name
	LegalName *string `json:"legalName,omitempty"`

	// OrganisationType Legal organisation type
	OrganisationType CommonOrganisationDetailV2OrganisationType `json:"organisationType"`

	// PhysicalAddresses Array is mandatory but may be empty if no valid addresses are held. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
	PhysicalAddresses []CommonPhysicalAddressWithPurpose `json:"physicalAddresses"`

	// RegisteredCountry Enumeration with values from [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country codes.  Assumed to be AUS if absent
	RegisteredCountry *string `json:"registeredCountry,omitempty"`

	// ShortName Short name used for communication, if different to the business name
	ShortName *string `json:"shortName,omitempty"`
}

// CommonOrganisationDetailV2IndustryCodeVersion The applicable [ANZSIC](http://www.abs.gov.au/ANZSIC) release version of the industry code provided. Should only be supplied if “industryCode“ is also supplied. If “industryCode“ is supplied but “industryCodeVersion“ is absent, default is “ANZSIC_1292.0_2006_V2.0“
type CommonOrganisationDetailV2IndustryCodeVersion string

// CommonOrganisationDetailV2OrganisationType Legal organisation type
type CommonOrganisationDetailV2OrganisationType string

// CommonOrganisationDetailV2AllOf defines model for CommonOrganisationDetailV2_allOf.
type CommonOrganisationDetailV2AllOf struct {
	// PhysicalAddresses Array is mandatory but may be empty if no valid addresses are held. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
	PhysicalAddresses []CommonPhysicalAddressWithPurpose `json:"physicalAddresses"`
}

// CommonPAFAddress Australian address formatted according to the file format defined by the [PAF file format](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf)
type CommonPAFAddress struct {
	// BuildingName1 Building/Property name 1
	BuildingName1 *string `json:"buildingName1,omitempty"`

	// BuildingName2 Building/Property name 2
	BuildingName2 *string `json:"buildingName2,omitempty"`

	// Dpid Unique identifier for an address as defined by Australia Post.  Also known as Delivery Point Identifier
	Dpid *string `json:"dpid,omitempty"`

	// FlatUnitNumber Unit number (including suffix, if applicable)
	FlatUnitNumber *string `json:"flatUnitNumber,omitempty"`

	// FlatUnitType Type of flat or unit for the address
	FlatUnitType *string `json:"flatUnitType,omitempty"`

	// FloorLevelNumber Floor or level number (including alpha characters)
	FloorLevelNumber *string `json:"floorLevelNumber,omitempty"`

	// FloorLevelType Type of floor or level for the address
	FloorLevelType *string `json:"floorLevelType,omitempty"`

	// LocalityName Full name of locality
	LocalityName string `json:"localityName"`

	// LotNumber Allotment number for the address
	LotNumber *string `json:"lotNumber,omitempty"`

	// PostalDeliveryNumber Postal delivery number if the address is a postal delivery type
	PostalDeliveryNumber *int `json:"postalDeliveryNumber,omitempty"`

	// PostalDeliveryNumberPrefix Postal delivery number prefix related to the postal delivery number
	PostalDeliveryNumberPrefix *string `json:"postalDeliveryNumberPrefix,omitempty"`

	// PostalDeliveryNumberSuffix Postal delivery number suffix related to the postal delivery number
	PostalDeliveryNumberSuffix *string `json:"postalDeliveryNumberSuffix,omitempty"`

	// PostalDeliveryType Postal delivery type. (eg. PO BOX). Valid enumeration defined by Australia Post PAF code file
	PostalDeliveryType *string `json:"postalDeliveryType,omitempty"`

	// Postcode Postcode for the locality
	Postcode string `json:"postcode"`

	// State State in which the address belongs. Valid enumeration defined by Australia Post PAF code file [State Type Abbreviation](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf). NSW, QLD, VIC, NT, WA, SA, TAS, ACT, AAT
	State string `json:"state"`

	// StreetName The name of the street
	StreetName *string `json:"streetName,omitempty"`

	// StreetSuffix The street type suffix. Valid enumeration defined by Australia Post PAF code file
	StreetSuffix *string `json:"streetSuffix,omitempty"`

	// StreetType The street type. Valid enumeration defined by Australia Post PAF code file
	StreetType *string `json:"streetType,omitempty"`

	// ThoroughfareNumber1 Thoroughfare number for a property (first number in a property ranged address)
	ThoroughfareNumber1 *int `json:"thoroughfareNumber1,omitempty"`

	// ThoroughfareNumber1Suffix Suffix for the thoroughfare number. Only relevant is thoroughfareNumber1 is populated
	ThoroughfareNumber1Suffix *string `json:"thoroughfareNumber1Suffix,omitempty"`

	// ThoroughfareNumber2 Second thoroughfare number (only used if the property has a ranged address eg 23-25)
	ThoroughfareNumber2 *int `json:"thoroughfareNumber2,omitempty"`

	// ThoroughfareNumber2Suffix Suffix for the second thoroughfare number. Only relevant is thoroughfareNumber2 is populated
	ThoroughfareNumber2Suffix *string `json:"thoroughfareNumber2Suffix,omitempty"`
}

// CommonPerson defines model for CommonPerson.
type CommonPerson struct {
	// FirstName For people with single names this field need not be present. The single name should be in the lastName field. Where a data holder cannot determine first and middle names from a collection of given names, a single string representing all given names MAY be provided.
	FirstName *string `json:"firstName,omitempty"`

	// LastName For people with single names the single name should be in this field
	LastName string `json:"lastName"`

	// LastUpdateTime The date and time that this record was last updated by the customer.  If no update has occurred then this date should reflect the initial creation date for the data
	LastUpdateTime *string `json:"lastUpdateTime,omitempty"`

	// MiddleNames Field is mandatory but array may be empty
	MiddleNames []string `json:"middleNames"`

	// OccupationCode Value is a valid **[[ANZSCO]](#iref-ANZSCO)** Standard Occupation classification code. If the occupation code held by the data holder is not one of the supported **[[ANZSCO]](#iref-ANZSCO)** versions, then it must not be supplied.
	OccupationCode *string `json:"occupationCode,omitempty"`

	// OccupationCodeVersion The applicable **[[ANZSCO]](#iref-ANZSCO)** release version of the occupation code provided. Mandatory if an ``occupationCode`` is supplied. If ``occupationCode`` is supplied but ``occupationCodeVersion`` is absent, default is ``ANZSCO_1220.0_2013_V1.2``
	OccupationCodeVersion *CommonPersonOccupationCodeVersion `json:"occupationCodeVersion,omitempty"`

	// Prefix Also known as title or salutation.  The prefix to the name (e.g. Mr, Mrs, Ms, Miss, Sir, etc)
	Prefix *string `json:"prefix,omitempty"`

	// Suffix Used for a trailing suffix to the name (e.g. Jr)
	Suffix *string `json:"suffix,omitempty"`
}

// CommonPersonOccupationCodeVersion The applicable **[[ANZSCO]](#iref-ANZSCO)** release version of the occupation code provided. Mandatory if an “occupationCode“ is supplied. If “occupationCode“ is supplied but “occupationCodeVersion“ is absent, default is “ANZSCO_1220.0_2013_V1.2“
type CommonPersonOccupationCodeVersion string

// CommonPersonDetailV2 defines model for CommonPersonDetailV2.
type CommonPersonDetailV2 struct {
	// EmailAddresses May be empty
	EmailAddresses []CommonEmailAddress `json:"emailAddresses"`

	// FirstName For people with single names this field need not be present. The single name should be in the lastName field. Where a data holder cannot determine first and middle names from a collection of given names, a single string representing all given names MAY be provided.
	FirstName *string `json:"firstName,omitempty"`

	// LastName For people with single names the single name should be in this field
	LastName string `json:"lastName"`

	// LastUpdateTime The date and time that this record was last updated by the customer.  If no update has occurred then this date should reflect the initial creation date for the data
	LastUpdateTime *string `json:"lastUpdateTime,omitempty"`

	// MiddleNames Field is mandatory but array may be empty
	MiddleNames []string `json:"middleNames"`

	// OccupationCode Value is a valid **[[ANZSCO]](#iref-ANZSCO)** Standard Occupation classification code. If the occupation code held by the data holder is not one of the supported **[[ANZSCO]](#iref-ANZSCO)** versions, then it must not be supplied.
	OccupationCode *string `json:"occupationCode,omitempty"`

	// OccupationCodeVersion The applicable **[[ANZSCO]](#iref-ANZSCO)** release version of the occupation code provided. Mandatory if an ``occupationCode`` is supplied. If ``occupationCode`` is supplied but ``occupationCodeVersion`` is absent, default is ``ANZSCO_1220.0_2013_V1.2``
	OccupationCodeVersion *CommonPersonDetailV2OccupationCodeVersion `json:"occupationCodeVersion,omitempty"`

	// PhoneNumbers Array is mandatory but may be empty if no phone numbers are held
	PhoneNumbers []CommonPhoneNumber `json:"phoneNumbers"`

	// PhysicalAddresses Array is mandatory but may be empty if no valid addresses are held. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
	PhysicalAddresses []CommonPhysicalAddressWithPurpose `json:"physicalAddresses"`

	// Prefix Also known as title or salutation.  The prefix to the name (e.g. Mr, Mrs, Ms, Miss, Sir, etc)
	Prefix *string `json:"prefix,omitempty"`

	// Suffix Used for a trailing suffix to the name (e.g. Jr)
	Suffix *string `json:"suffix,omitempty"`
}

// CommonPersonDetailV2OccupationCodeVersion The applicable **[[ANZSCO]](#iref-ANZSCO)** release version of the occupation code provided. Mandatory if an “occupationCode“ is supplied. If “occupationCode“ is supplied but “occupationCodeVersion“ is absent, default is “ANZSCO_1220.0_2013_V1.2“
type CommonPersonDetailV2OccupationCodeVersion string

// CommonPersonDetailV2AllOf defines model for CommonPersonDetailV2_allOf.
type CommonPersonDetailV2AllOf struct {
	// EmailAddresses May be empty
	EmailAddresses []CommonEmailAddress `json:"emailAddresses"`

	// PhoneNumbers Array is mandatory but may be empty if no phone numbers are held
	PhoneNumbers []CommonPhoneNumber `json:"phoneNumbers"`

	// PhysicalAddresses Array is mandatory but may be empty if no valid addresses are held. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
	PhysicalAddresses []CommonPhysicalAddressWithPurpose `json:"physicalAddresses"`
}

// CommonPhoneNumber defines model for CommonPhoneNumber.
type CommonPhoneNumber struct {
	// AreaCode Required for non Mobile Phones, if field is present and refers to Australian code - the leading 0 should be omitted.
	AreaCode *string `json:"areaCode,omitempty"`

	// CountryCode If absent, assumed to be Australia (+61). The + should be included
	CountryCode *string `json:"countryCode,omitempty"`

	// Extension An extension number (if applicable)
	Extension *string `json:"extension,omitempty"`

	// FullNumber Fully formatted phone number with country code, area code, number and extension incorporated. Formatted according to section 5.1.4. of **[[RFC3966]](#iref-RFC3966)**
	FullNumber string `json:"fullNumber"`

	// IsPreferred May be true for one and only one entry to indicate the preferred phone number. Assumed to be 'false' if not present
	IsPreferred *bool `json:"isPreferred,omitempty"`

	// Number The actual phone number, with leading zeros as appropriate
	Number string `json:"number"`

	// Purpose The purpose of the number as specified by the customer
	Purpose CommonPhoneNumberPurpose `json:"purpose"`
}

// CommonPhoneNumberPurpose The purpose of the number as specified by the customer
type CommonPhoneNumberPurpose string

// CommonPhysicalAddress defines model for CommonPhysicalAddress.
type CommonPhysicalAddress struct {
	// AddressUType The type of address object present
	AddressUType CommonPhysicalAddressAddressUType `json:"addressUType"`

	// Paf Australian address formatted according to the file format defined by the [PAF file format](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf)
	Paf    *CommonPAFAddress    `json:"paf,omitempty"`
	Simple *CommonSimpleAddress `json:"simple,omitempty"`
}

// CommonPhysicalAddressAddressUType The type of address object present
type CommonPhysicalAddressAddressUType string

// CommonPhysicalAddressWithPurpose defines model for CommonPhysicalAddressWithPurpose.
type CommonPhysicalAddressWithPurpose struct {
	// AddressUType The type of address object present
	AddressUType CommonPhysicalAddressWithPurposeAddressUType `json:"addressUType"`

	// Paf Australian address formatted according to the file format defined by the [PAF file format](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf)
	Paf *CommonPAFAddress `json:"paf,omitempty"`

	// Purpose Enumeration of values indicating the purpose of the physical address
	Purpose CommonPhysicalAddressWithPurposePurpose `json:"purpose"`
	Simple  *CommonSimpleAddress                    `json:"simple,omitempty"`
}

// CommonPhysicalAddressWithPurposeAddressUType The type of address object present
type CommonPhysicalAddressWithPurposeAddressUType string

// CommonPhysicalAddressWithPurposePurpose Enumeration of values indicating the purpose of the physical address
type CommonPhysicalAddressWithPurposePurpose string

// CommonPhysicalAddressWithPurposeAllOf defines model for CommonPhysicalAddressWithPurpose_allOf.
type CommonPhysicalAddressWithPurposeAllOf struct {
	// Purpose Enumeration of values indicating the purpose of the physical address
	Purpose CommonPhysicalAddressWithPurposeAllOfPurpose `json:"purpose"`
}

// CommonPhysicalAddressWithPurposeAllOfPurpose Enumeration of values indicating the purpose of the physical address
type CommonPhysicalAddressWithPurposeAllOfPurpose string

// CommonSimpleAddress defines model for CommonSimpleAddress.
type CommonSimpleAddress struct {
	// AddressLine1 First line of the standard address object
	AddressLine1 string `json:"addressLine1"`

	// AddressLine2 Second line of the standard address object
	AddressLine2 *string `json:"addressLine2,omitempty"`

	// AddressLine3 Third line of the standard address object
	AddressLine3 *string `json:"addressLine3,omitempty"`

	// City Name of the city or locality
	City string `json:"city"`

	// Country A valid [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country code. Australia (AUS) is assumed if country is not present.
	Country *string `json:"country,omitempty"`

	// MailingName Name of the individual or business formatted for inclusion in an address used for physical mail
	MailingName *string `json:"mailingName,omitempty"`

	// Postcode Mandatory for Australian addresses
	Postcode *string `json:"postcode,omitempty"`

	// State Free text if the country is not Australia. If country is Australia then must be one of the values defined by the [State Type Abbreviation](https://auspost.com.au/content/dam/auspost_corp/media/documents/australia-post-data-guide.pdf) in the PAF file format. NSW, QLD, VIC, NT, WA, SA, TAS, ACT, AAT
	State string `json:"state"`
}

// DiscoveryOutage defines model for DiscoveryOutage.
type DiscoveryOutage struct {
	// Duration Planned duration of the outage. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) (excludes recurrence syntax)
	Duration string `json:"duration"`

	// Explanation Provides an explanation of the current outage that can be displayed to an end customer
	Explanation string `json:"explanation"`

	// IsPartial Flag that indicates, if present and set to true, that the outage is only partial meaning that only a subset of normally available end points will be affected by the outage
	IsPartial *bool `json:"isPartial,omitempty"`

	// OutageTime Date and time that the outage is scheduled to begin
	OutageTime string `json:"outageTime"`
}

// Links defines model for Links.
type Links struct {
	// Self Fully qualified link that generated the current response document
	Self string `json:"self"`
}

// Meta defines model for Meta.
type Meta = map[string]interface{}

// MetaError Additional data for customised error codes
type MetaError struct {
	// Urn The CDR error code URN which the application-specific error code extends. Mandatory if the error `code` is an application-specific error rather than a standardised error code.
	Urn *string `json:"urn,omitempty"`
}

// ResponseCommonCustomer defines model for ResponseCommonCustomer.
type ResponseCommonCustomer struct {
	Data  ResponseCommonCustomerData `json:"data"`
	Links Links                      `json:"links"`
	Meta  *Meta                      `json:"meta,omitempty"`
}

// ResponseCommonCustomerDetailV2 defines model for ResponseCommonCustomerDetailV2.
type ResponseCommonCustomerDetailV2 struct {
	Data  ResponseCommonCustomerDetailV2Data `json:"data"`
	Links Links                              `json:"links"`
	Meta  *Meta                              `json:"meta,omitempty"`
}

// ResponseCommonCustomerDetailV2Data defines model for ResponseCommonCustomerDetailV2_data.
type ResponseCommonCustomerDetailV2Data struct {
	// CustomerUType The type of customer object that is present
	CustomerUType ResponseCommonCustomerDetailV2DataCustomerUType `json:"customerUType"`
	Organisation  *CommonOrganisationDetailV2                     `json:"organisation,omitempty"`
	Person        *CommonPersonDetailV2                           `json:"person,omitempty"`
}

// ResponseCommonCustomerDetailV2DataCustomerUType The type of customer object that is present
type ResponseCommonCustomerDetailV2DataCustomerUType string

// ResponseCommonCustomerData defines model for ResponseCommonCustomer_data.
type ResponseCommonCustomerData struct {
	// CustomerUType The type of customer object that is present
	CustomerUType ResponseCommonCustomerDataCustomerUType `json:"customerUType"`
	Organisation  *CommonOrganisation                     `json:"organisation,omitempty"`
	Person        *CommonPerson                           `json:"person,omitempty"`
}

// ResponseCommonCustomerDataCustomerUType The type of customer object that is present
type ResponseCommonCustomerDataCustomerUType string

// ResponseCommonDiscoveryStatus defines model for ResponseCommonDiscoveryStatus.
type ResponseCommonDiscoveryStatus struct {
	Data  ResponseCommonDiscoveryStatusData `json:"data"`
	Links Links                             `json:"links"`
	Meta  *Meta                             `json:"meta,omitempty"`
}

// ResponseCommonDiscoveryStatusData defines model for ResponseCommonDiscoveryStatus_data.
type ResponseCommonDiscoveryStatusData struct {
	// DetectionTime The date and time that the current outage was detected. Should only be present if the status property is PARTIAL_FAILURE or UNAVAILABLE
	DetectionTime *string `json:"detectionTime,omitempty"`

	// ExpectedResolutionTime The date and time that full service is expected to resume (if known). Should not be present if the status property has a value of OK.
	ExpectedResolutionTime *string `json:"expectedResolutionTime,omitempty"`

	// Explanation Provides an explanation of the current outage that can be displayed to an end customer. Mandatory if the status property is any value other than OK
	Explanation *string `json:"explanation,omitempty"`

	// Status Enumeration with values. OK (implementation is fully functional). PARTIAL_FAILURE (one or more end points are unexpectedly unavailable). UNAVAILABLE (the full implementation is unexpectedly unavailable). SCHEDULED_OUTAGE (an advertised outage is in effect)
	Status ResponseCommonDiscoveryStatusDataStatus `json:"status"`

	// UpdateTime The date and time that this status was last updated by the Data Holder.
	UpdateTime string `json:"updateTime"`
}

// ResponseCommonDiscoveryStatusDataStatus Enumeration with values. OK (implementation is fully functional). PARTIAL_FAILURE (one or more end points are unexpectedly unavailable). UNAVAILABLE (the full implementation is unexpectedly unavailable). SCHEDULED_OUTAGE (an advertised outage is in effect)
type ResponseCommonDiscoveryStatusDataStatus string

// ResponseDiscoveryOutagesList defines model for ResponseDiscoveryOutagesList.
type ResponseDiscoveryOutagesList struct {
	Data  ResponseDiscoveryOutagesListData `json:"data"`
	Links Links                            `json:"links"`
	Meta  *Meta                            `json:"meta,omitempty"`
}

// ResponseDiscoveryOutagesListData defines model for ResponseDiscoveryOutagesList_data.
type ResponseDiscoveryOutagesListData struct {
	// Outages List of scheduled outages. Property is mandatory but may contain and empty list if no outages are scheduled
	Outages []DiscoveryOutage `json:"outages"`
}

// ResponseErrorListV2 defines model for ResponseErrorListV2.
type ResponseErrorListV2 struct {
	Errors []ResponseErrorListV2Errors `json:"errors"`
}

// ResponseErrorListV2Errors defines model for ResponseErrorListV2_errors.
type ResponseErrorListV2Errors struct {
	// Code The code of the error encountered. Where the error is specific to the respondent, an application-specific error code, expressed as a string value. If the error is application-specific, the URN code that the specific error extends must be provided in the meta object. Otherwise, the value is the error code URN.
	Code string `json:"code"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Meta Additional data for customised error codes
	Meta *MetaError `json:"meta,omitempty"`

	// Title A short, human-readable summary of the problem that MUST NOT change from occurrence to occurrence of the problem represented by the error code.
	Title string `json:"title"`
}

// GetCustomerParams defines parameters for GetCustomer.
type GetCustomerParams struct {
	// XV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
	XV string `json:"x-v"`

	// XMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.
	XMinV *string `json:"x-min-v,omitempty"`

	// XFapiInteractionId An **[[RFC4122]](#nref-RFC4122)** UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a **[[RFC4122]](#nref-RFC4122)** UUID value is required to be provided in the response header to track the interaction.
	XFapiInteractionId *string `json:"x-fapi-interaction-id,omitempty"`

	// XFapiAuthDate The time when the customer last logged in to the Data Recipient Software Product as described in **[[FAPI-1.0-Baseline]](#nref-FAPI-1-0-Baseline)**.  Required for all resource calls (customer present and unattended). Not required for unauthenticated calls.
	XFapiAuthDate *string `json:"x-fapi-auth-date,omitempty"`

	// XFapiCustomerIpAddress The customer's original IP address if the customer is currently logged in to the Data Recipient Software Product. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.
	XFapiCustomerIpAddress *string `json:"x-fapi-customer-ip-address,omitempty"`

	// XCdsClientHeaders The customer's original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the Data Recipient Software Product. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.
	XCdsClientHeaders *string `json:"x-cds-client-headers,omitempty"`
}

// GetCustomerDetailParams defines parameters for GetCustomerDetail.
type GetCustomerDetailParams struct {
	// XV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
	XV string `json:"x-v"`

	// XMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.
	XMinV *string `json:"x-min-v,omitempty"`

	// XFapiInteractionId An **[[RFC4122]](#nref-RFC4122)** UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a **[[RFC4122]](#nref-RFC4122)** UUID value is required to be provided in the response header to track the interaction.
	XFapiInteractionId *string `json:"x-fapi-interaction-id,omitempty"`

	// XFapiAuthDate The time when the customer last logged in to the Data Recipient Software Product as described in **[[FAPI-1.0-Baseline]](#nref-FAPI-1-0-Baseline)**.  Required for all resource calls (customer present and unattended). Not required for unauthenticated calls.
	XFapiAuthDate *string `json:"x-fapi-auth-date,omitempty"`

	// XFapiCustomerIpAddress The customer's original IP address if the customer is currently logged in to the Data Recipient Software Product. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.
	XFapiCustomerIpAddress *string `json:"x-fapi-customer-ip-address,omitempty"`

	// XCdsClientHeaders The customer's original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the Data Recipient Software Product. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.
	XCdsClientHeaders *string `json:"x-cds-client-headers,omitempty"`
}

// GetOutagesParams defines parameters for GetOutages.
type GetOutagesParams struct {
	// XV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
	XV string `json:"x-v"`

	// XMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.
	XMinV *string `json:"x-min-v,omitempty"`
}

// GetStatusParams defines parameters for GetStatus.
type GetStatusParams struct {
	// XV Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
	XV string `json:"x-v"`

	// XMinV Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder must respond with a 406 Not Acceptable.
	XMinV *string `json:"x-min-v,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCustomer request
	GetCustomer(ctx context.Context, params *GetCustomerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCustomerDetail request
	GetCustomerDetail(ctx context.Context, params *GetCustomerDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOutages request
	GetOutages(ctx context.Context, params *GetOutagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatus request
	GetStatus(ctx context.Context, params *GetStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCustomer(ctx context.Context, params *GetCustomerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomerRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCustomerDetail(ctx context.Context, params *GetCustomerDetailParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomerDetailRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOutages(ctx context.Context, params *GetOutagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOutagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatus(ctx context.Context, params *GetStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatusRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCustomerRequest generates requests for GetCustomer
func NewGetCustomerRequest(server string, params *GetCustomerParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/common/customer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-v", runtime.ParamLocationHeader, params.XV)
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-v", headerParam0)

		if params.XMinV != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "x-min-v", runtime.ParamLocationHeader, *params.XMinV)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-min-v", headerParam1)
		}

		if params.XFapiInteractionId != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-interaction-id", runtime.ParamLocationHeader, *params.XFapiInteractionId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-interaction-id", headerParam2)
		}

		if params.XFapiAuthDate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-auth-date", runtime.ParamLocationHeader, *params.XFapiAuthDate)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-auth-date", headerParam3)
		}

		if params.XFapiCustomerIpAddress != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-customer-ip-address", runtime.ParamLocationHeader, *params.XFapiCustomerIpAddress)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-customer-ip-address", headerParam4)
		}

		if params.XCdsClientHeaders != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "x-cds-client-headers", runtime.ParamLocationHeader, *params.XCdsClientHeaders)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-cds-client-headers", headerParam5)
		}

	}

	return req, nil
}

// NewGetCustomerDetailRequest generates requests for GetCustomerDetail
func NewGetCustomerDetailRequest(server string, params *GetCustomerDetailParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/common/customer/detail")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-v", runtime.ParamLocationHeader, params.XV)
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-v", headerParam0)

		if params.XMinV != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "x-min-v", runtime.ParamLocationHeader, *params.XMinV)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-min-v", headerParam1)
		}

		if params.XFapiInteractionId != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-interaction-id", runtime.ParamLocationHeader, *params.XFapiInteractionId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-interaction-id", headerParam2)
		}

		if params.XFapiAuthDate != nil {
			var headerParam3 string

			headerParam3, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-auth-date", runtime.ParamLocationHeader, *params.XFapiAuthDate)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-auth-date", headerParam3)
		}

		if params.XFapiCustomerIpAddress != nil {
			var headerParam4 string

			headerParam4, err = runtime.StyleParamWithLocation("simple", false, "x-fapi-customer-ip-address", runtime.ParamLocationHeader, *params.XFapiCustomerIpAddress)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-fapi-customer-ip-address", headerParam4)
		}

		if params.XCdsClientHeaders != nil {
			var headerParam5 string

			headerParam5, err = runtime.StyleParamWithLocation("simple", false, "x-cds-client-headers", runtime.ParamLocationHeader, *params.XCdsClientHeaders)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-cds-client-headers", headerParam5)
		}

	}

	return req, nil
}

// NewGetOutagesRequest generates requests for GetOutages
func NewGetOutagesRequest(server string, params *GetOutagesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery/outages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-v", runtime.ParamLocationHeader, params.XV)
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-v", headerParam0)

		if params.XMinV != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "x-min-v", runtime.ParamLocationHeader, *params.XMinV)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-min-v", headerParam1)
		}

	}

	return req, nil
}

// NewGetStatusRequest generates requests for GetStatus
func NewGetStatusRequest(server string, params *GetStatusParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "x-v", runtime.ParamLocationHeader, params.XV)
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-v", headerParam0)

		if params.XMinV != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "x-min-v", runtime.ParamLocationHeader, *params.XMinV)
			if err != nil {
				return nil, err
			}

			req.Header.Set("x-min-v", headerParam1)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCustomerWithResponse request
	GetCustomerWithResponse(ctx context.Context, params *GetCustomerParams, reqEditors ...RequestEditorFn) (*GetCustomerResponse, error)

	// GetCustomerDetailWithResponse request
	GetCustomerDetailWithResponse(ctx context.Context, params *GetCustomerDetailParams, reqEditors ...RequestEditorFn) (*GetCustomerDetailResponse, error)

	// GetOutagesWithResponse request
	GetOutagesWithResponse(ctx context.Context, params *GetOutagesParams, reqEditors ...RequestEditorFn) (*GetOutagesResponse, error)

	// GetStatusWithResponse request
	GetStatusWithResponse(ctx context.Context, params *GetStatusParams, reqEditors ...RequestEditorFn) (*GetStatusResponse, error)
}

type GetCustomerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResponseCommonCustomer
	JSON400      *ResponseErrorListV2
	JSON406      *ResponseErrorListV2
}

// Status returns HTTPResponse.Status
func (r GetCustomerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCustomerDetailResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResponseCommonCustomerDetailV2
	JSON400      *ResponseErrorListV2
	JSON406      *ResponseErrorListV2
}

// Status returns HTTPResponse.Status
func (r GetCustomerDetailResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomerDetailResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOutagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResponseDiscoveryOutagesList
	JSON400      *ResponseErrorListV2
	JSON406      *ResponseErrorListV2
}

// Status returns HTTPResponse.Status
func (r GetOutagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOutagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ResponseCommonDiscoveryStatus
	JSON400      *ResponseErrorListV2
	JSON406      *ResponseErrorListV2
}

// Status returns HTTPResponse.Status
func (r GetStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCustomerWithResponse request returning *GetCustomerResponse
func (c *ClientWithResponses) GetCustomerWithResponse(ctx context.Context, params *GetCustomerParams, reqEditors ...RequestEditorFn) (*GetCustomerResponse, error) {
	rsp, err := c.GetCustomer(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomerResponse(rsp)
}

// GetCustomerDetailWithResponse request returning *GetCustomerDetailResponse
func (c *ClientWithResponses) GetCustomerDetailWithResponse(ctx context.Context, params *GetCustomerDetailParams, reqEditors ...RequestEditorFn) (*GetCustomerDetailResponse, error) {
	rsp, err := c.GetCustomerDetail(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomerDetailResponse(rsp)
}

// GetOutagesWithResponse request returning *GetOutagesResponse
func (c *ClientWithResponses) GetOutagesWithResponse(ctx context.Context, params *GetOutagesParams, reqEditors ...RequestEditorFn) (*GetOutagesResponse, error) {
	rsp, err := c.GetOutages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOutagesResponse(rsp)
}

// GetStatusWithResponse request returning *GetStatusResponse
func (c *ClientWithResponses) GetStatusWithResponse(ctx context.Context, params *GetStatusParams, reqEditors ...RequestEditorFn) (*GetStatusResponse, error) {
	rsp, err := c.GetStatus(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatusResponse(rsp)
}

// ParseGetCustomerResponse parses an HTTP response from a GetCustomerWithResponse call
func ParseGetCustomerResponse(rsp *http.Response) (*GetCustomerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResponseCommonCustomer
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 406:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON406 = &dest

	}

	return response, nil
}

// ParseGetCustomerDetailResponse parses an HTTP response from a GetCustomerDetailWithResponse call
func ParseGetCustomerDetailResponse(rsp *http.Response) (*GetCustomerDetailResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomerDetailResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResponseCommonCustomerDetailV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 406:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON406 = &dest

	}

	return response, nil
}

// ParseGetOutagesResponse parses an HTTP response from a GetOutagesWithResponse call
func ParseGetOutagesResponse(rsp *http.Response) (*GetOutagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOutagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResponseDiscoveryOutagesList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 406:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON406 = &dest

	}

	return response, nil
}

// ParseGetStatusResponse parses an HTTP response from a GetStatusWithResponse call
func ParseGetStatusResponse(rsp *http.Response) (*GetStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ResponseCommonDiscoveryStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 406:
		var dest ResponseErrorListV2
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON406 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Customer
	// (GET /common/customer)
	GetCustomer(ctx echo.Context, params GetCustomerParams) error
	// Get Customer Detail
	// (GET /common/customer/detail)
	GetCustomerDetail(ctx echo.Context, params GetCustomerDetailParams) error
	// Get Outages
	// (GET /discovery/outages)
	GetOutages(ctx echo.Context, params GetOutagesParams) error
	// Get Status
	// (GET /discovery/status)
	GetStatus(ctx echo.Context, params GetStatusParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomer(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-v: %s", err))
		}

		params.XV = XV
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-v is required, but not found"))
	}
	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-min-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-min-v: %s", err))
		}

		params.XMinV = &XMinV
	}
	// ------------- Optional header parameter "x-fapi-interaction-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-interaction-id")]; found {
		var XFapiInteractionId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-interaction-id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-interaction-id", valueList[0], &XFapiInteractionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-interaction-id: %s", err))
		}

		params.XFapiInteractionId = &XFapiInteractionId
	}
	// ------------- Optional header parameter "x-fapi-auth-date" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-auth-date")]; found {
		var XFapiAuthDate string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-auth-date, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-auth-date", valueList[0], &XFapiAuthDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-auth-date: %s", err))
		}

		params.XFapiAuthDate = &XFapiAuthDate
	}
	// ------------- Optional header parameter "x-fapi-customer-ip-address" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-customer-ip-address")]; found {
		var XFapiCustomerIpAddress string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-customer-ip-address, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-customer-ip-address", valueList[0], &XFapiCustomerIpAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-customer-ip-address: %s", err))
		}

		params.XFapiCustomerIpAddress = &XFapiCustomerIpAddress
	}
	// ------------- Optional header parameter "x-cds-client-headers" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-cds-client-headers")]; found {
		var XCdsClientHeaders string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-cds-client-headers, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-cds-client-headers", valueList[0], &XCdsClientHeaders, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-cds-client-headers: %s", err))
		}

		params.XCdsClientHeaders = &XCdsClientHeaders
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomer(ctx, params)
	return err
}

// GetCustomerDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomerDetail(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerDetailParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-v: %s", err))
		}

		params.XV = XV
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-v is required, but not found"))
	}
	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-min-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-min-v: %s", err))
		}

		params.XMinV = &XMinV
	}
	// ------------- Optional header parameter "x-fapi-interaction-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-interaction-id")]; found {
		var XFapiInteractionId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-interaction-id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-interaction-id", valueList[0], &XFapiInteractionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-interaction-id: %s", err))
		}

		params.XFapiInteractionId = &XFapiInteractionId
	}
	// ------------- Optional header parameter "x-fapi-auth-date" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-auth-date")]; found {
		var XFapiAuthDate string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-auth-date, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-auth-date", valueList[0], &XFapiAuthDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-auth-date: %s", err))
		}

		params.XFapiAuthDate = &XFapiAuthDate
	}
	// ------------- Optional header parameter "x-fapi-customer-ip-address" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-customer-ip-address")]; found {
		var XFapiCustomerIpAddress string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-fapi-customer-ip-address, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-customer-ip-address", valueList[0], &XFapiCustomerIpAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-fapi-customer-ip-address: %s", err))
		}

		params.XFapiCustomerIpAddress = &XFapiCustomerIpAddress
	}
	// ------------- Optional header parameter "x-cds-client-headers" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-cds-client-headers")]; found {
		var XCdsClientHeaders string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-cds-client-headers, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-cds-client-headers", valueList[0], &XCdsClientHeaders, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-cds-client-headers: %s", err))
		}

		params.XCdsClientHeaders = &XCdsClientHeaders
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomerDetail(ctx, params)
	return err
}

// GetOutages converts echo context to params.
func (w *ServerInterfaceWrapper) GetOutages(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOutagesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-v: %s", err))
		}

		params.XV = XV
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-v is required, but not found"))
	}
	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-min-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-min-v: %s", err))
		}

		params.XMinV = &XMinV
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOutages(ctx, params)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatusParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-v: %s", err))
		}

		params.XV = XV
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-v is required, but not found"))
	}
	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-min-v, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-min-v: %s", err))
		}

		params.XMinV = &XMinV
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/common/customer", wrapper.GetCustomer)
	router.GET(baseURL+"/common/customer/detail", wrapper.GetCustomerDetail)
	router.GET(baseURL+"/discovery/outages", wrapper.GetOutages)
	router.GET(baseURL+"/discovery/status", wrapper.GetStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9C28bObLuXyE6Fxg725Jf2eCugQWu4sdEO7ala8mZM+sYNtVNSdywyR6SbVtn4P9+",
	"wCL7KbYsJ96cnDnCYrGxml0sFquKXz3Y+0cQiSQVnHCtgsM/AhXNSYLhn0ciSQQ/STBlvTiWRMGvqRQp",
	"kZoS+AuXD2KiIklTTQUPDoMeioSUJNJsgaZCJlhrEiNiiCH3UoiwQjGZUk5iNFkgPSfwqKNSErmXEOXo",
	"7dvr68vTo78e7O/f3Gy94ZJMO+7v7bdvgzDQi5QEh4HSkvJZEAaPnShWHffryaMmkmN2SabBUxhQNZRk",
	"SqQk8TLT53iBJgRpmREzPxKcIMxjJDhbwB+Wf0kiIWPDmmE5EoyRyFDoomPChSYKfo/JFGdM19dccjsR",
	"ghHMm+x+cD8/hUGayVQosszmeE6QewhsmtlgFpCokR6d0lKmUaa0SIhEWyc8S4jEhsx2EAaEZ0lweB18",
	"HJyfBGEwGH88uQzC4OpiNDw56p/2T46DMPh1cPlLcNMU8tNTGEjye0ZBjtdBubyc6/IVMfkXibRZkdWo",
	"gZxhThW2q1nSqAn3aFOmtMSMYo4+ZIpyohS6yJIJkYUARJXqErthgKPVdI9EkmK+WEW2iy7dkq1G0CnC",
	"HPWOLhBVCKcpoxGeMOJ9FwFDPr5mhOtTKpW+wEnLZk/NY8RxQpCYAmnKY3pP4wwzlEpxT2PKZwhHkRGM",
	"4GhC5phN88H1NZwKiVIiUkbQA9VzpCifMQLUjeJShaaUsBhxQmLEhTYWkUqiCNddhAw7lTeQmouMxWaM",
	"MweG7UosldYVn+FVCzZEvtN6Vy4nF0brMi4Fa1mCFMzHPY0J19Y8sZ0e6KCHuTBaVFlcpudCFqtAJ48p",
	"iYwP1cKwlykSg6LFVKUML4zvsf5GC3TFSydALQvADlWwoV+4ePDayMTZln9jLir78Zy1EaXxhFE1TwjX",
	"x1i3CCnGmiybih03ITF6wAoVpEj8nK83E40KHiiPjXkvjkRMfAfUPWY0Rte9i3+O+kc3W3Ot08OdnYeH",
	"hy6eqO5M3HdxtmOfbqNIxKTFKfSLTYbp7NC5MSHngGOsMZoLFhOZb4E5TJwoVZamQpqdXZOVeyIVFVyF",
	"5nWOqEZJZszFmqohxyiJuy89GCvS+mRnsEIDrTICg+lv9/b/tt/dvd3f3X1/+2m/uxuEnn2tOMM1FyUJ",
	"I1iRfHEVy6kI1VoHibtoZO0U3HBl0Ubb7+6qS7m7A+fMlCglY3bMN6qgMsl0Y4CTiKM2Mc4wLE54qtDd",
	"XYt47u4qB61vzB6IsE24Nx7boqp3dHF0SWZUaeLFMWMDYOgUyWKMdX1GoubdLkKnmCkYw4Xuoh6sCAmJ",
	"eMaY+xlFgk+pTGq69DxsMb77KjWWPabJKrs3yErTxDgArK2zdcjKmD0cARnQWUIysINcuMdojhUSUZQZ",
	"UGdtAojBM+fQJZkakOZ0imqKGYokcf7GDMxt2xjrOn7GLK70NYzMMPO7zTPzCE6X0Ag2ptMpkUbaWsCE",
	"udOFIT5fWvU2Y3jon8IHN3LNOxqcD3sXvwVh8PPg08nlxfnJxfj25GLcH/9WQX7D3uX44uRy9LE/DMJg",
	"NDg7uR1f9o7h2fjyajT26mOpZUci41oulhmsAE+rifeYZUShqRQJuu6PBuhg7/171GPpHHcOrK9QzllQ",
	"JbpCznaoEh0zqhPZWTrGJajuXCfMuGf4DdnfEOoplSXFYdm7GgFYAy1/oV9UcyFbkMrIPLK4oTiOI5Ek",
	"GacRrPWrNryJrGtoqQo7Gue1R1GWMDgsVfCYmiGYGfo+v3/jxerHRGPKPu0DSmdsMA0Or/8I/o8k0+Aw",
	"eLNTxpE7Lojc8eD9p/Clr+TT3to5n1Yz50YthRXpfKFohPNIlvhCVinxwjjzBPMYayEXcBAkNigkSaoX",
	"1jM65IBzUghLe+B30aAZMbpBQGWO7y3ayYM3MUWXJz/3R+OTy5PjLvonkQLZsDMEKlygREhwkNz+6hxk",
	"G7XzXv8MnON/GlLOFZLKJAU/VDWBpAkggzCgmiQgnOd3aViX6a9Uz4cu+nsqNA8bqS5p9fJ2tMeLw95p",
	"rzXNUAZw+crKbAOOjLAMmHaWN6U2OkuwbiYeroe90+rz0gfhTKVC6W4kEgNYIsE14Xonxkn+6DYSMt1J",
	"SEzxTiyiLAFZ4Zy1jhnTMedKZ5bRmHTTeGrC77qCTjLKDK/GlveWF/rBPd4Z2rcW1u/s+WF8SWp/bVL7",
	"PlJxSj344orT3w3CyGMZGy5X9qCe2Ck2CQ2NIBHqGTgGUYgZeUwYvSdygYaCco36BVUfQ1OG9RWn2obp",
	"XtY04jaG36I8YhkogMqmU/oI/rjEpturJvCftOZXY2hmlDHVzEyXQ4elHE+VqhDyjNwT1sb4qRlhSDIz",
	"yrMEbA5HFM2xxJEmUm2vnuc5/muzrbECJiLMqF74j8JTAxvzgD0f6ifTunU9xoQ2tpMvfg2ujGlhlmtQ",
	"G+UhjEJxrmiOvguNKy4Ro7QxtJ62oVyTGShmDTIMhaKa3pO+e9zC2FCSKX1cm70UhpvICLu4H7y9d/C6",
	"shmBHazNgjWb12LBr5JDj8S7aIvMumg4QB8G/7HdRZ/gwCUVFNnqXpBx5DZap4y0MRV5cwJD96TQvFWa",
	"rLQ3rTEyPyPK0cOcRvOagk0IE3ymvmE56NqSBzPuTSaS3FMg8O8+rrroYvRriP7/2XGIPvWPQnQxDtGv",
	"vRCNeiEa90Yh6h2NQ9Trjf2ikoSsSPdVM312bDuVNg0eF++CBjnVfWXVsRO0uNY6A688s54LKbLZfIol",
	"saa852OhHFR1ohil+VG/5XLJzgPy6jOJ+YwUuHb7a9yeh822DbO/F6aml3k3cJotIDV0jznkWTz0IW0q",
	"0gxc1Hqi84CiETFxkY8LtAVgHnCyOzEKic2xOTPqckNkhvYPOvt/fSUB7q8pQNW6grXkuP+MHBsAvgYH",
	"Kj4194sr4DyRylf4mbbXQL6pZPHCikUX/TonkiBcS9tGmBu6MdFEJpTnJRkTpCU0jgtmIKGBKzVB49Zm",
	"9J5wOyBEOGfGChZJ4ji1GI9VR6Pz3m92LS7v6UVU+CvF9tWVj++S4fvhUnx2n42kPXHoKejfUu4Agt9a",
	"BqEaYS97qlrIHAZmxSkswF/D+IRZRixutSmJt2+vId9+NLi52XpDJZl27J/bb9+ikTa8yRgNCrIoYlgp",
	"OnX5KjiCioKGqAz72pLGSob+PYWMutBaSxlHg9u9/f1dyLbvHdx+2uvuP1fKWLmYlgJGU4hlCeO80BRb",
	"R767q3Ner0m4osWqIa5s4V3/M4ULjzCWChfVMfXCxfKTPc+TUsj+Jwfe5HLaEjPVUwiaakZMOKswy3Re",
	"MoU+CRtEucgFPN0W6c666FyG6FyqEJ2b/1KlQjSiMkRER97IWrWcwld5/gwjLTFlZbbBM+k/5PbzJ2uZ",
	"6626nHVyuX7Vv2kcvV+bx3UH93oZ3PpUy7lb7/MlTEAqzUc+t3ve4lmf56/W1uRxvelccIeMvilVDHQc",
	"DisTxS/Nsxa8+FndpLZ/oNR2Q2cbqhS+LPVd2fnlTilJsB8XFG1KZvFccHQuJpQRBOQUZEGnOWBx6BM2",
	"BTrjQHqVvDocWx2LlAmGVORuBS2KhGrdAk1dVc7PZH9anEe4Xq0rQuOtv7zf27YI/i81gBqxLPYHe+RR",
	"E16e+DUj4Kh4WuZXn08IZ6w9aZuxWn9j1dot5q4WJkNjTdj90w0yYi+5ojwSMhXSQGLoXPJVMpSLLP7a",
	"3eu+6xrbcB2SB397/75AJu7v794hCavVAnqeory9J80p1iTUbZRpf5pipshPefuB08yX9B7wln0CIBdp",
	"aB+rMBDaPcrV2ngWqF3g1FiapCaQ9WGSdRozHf7Lt3lFX+ZyJ2b/YnxyedEb9wcXvbMgDM4HH/pn39qi",
	"WdHjQlAr2jU98KJwOJVjvO7MWhuEr9pzZtqVJHL3beev7H4unBRPgzBQNEkZ8WNFPF3Tu5cVxaeC4lpv",
	"jmBs8bK/C/Zq7eK7m9qy3irV6unzUszW2J81wVvr/B4g99zY5VJ8m/lUu0TENO8RcY4EnN+yfeWnaaVI",
	"lOuLQQzV5paPv436R2BPJWhY23qeb2uuq0abIZxR7ivvQgMwYrQSQ+fRet0uvJ2oJen2zOa30z7w2S+V",
	"X006onqxusvUjIAi5YoyTFTtOSoC/KvRUjBfNHy+crtRtwpYelejbYi03cFGp8VYlybJ85IvPJUTG1o+",
	"35lb6TUWsuw1KjGKObYBQTnEUa3bF4i5MCsHnV9QRCvzGobQcoMGUS+opp1KQpAmjzpPvTekWZCH0KDy",
	"sNwTCBUgsWTQaqmpzr00+0D+mwpseTK60YbyLXU3/+FkHZCzvtZsveesKnbc+P5jqiJxT+RikGk8I8vu",
	"Ls5kccGjUWRlmBuB5yOKTBlQakW9YLb/9/3uHjp2L6pyTwjvPtAvNDUiB+s1f+30R4Nb88ab4o1ttEUe",
	"IXiATHQmJeERQWrBNX7cfqFJkseUYd62SpvnU8a6KgMLzwZTa7domx+PMDcq6hr6LSo2b/O4ChU97cBD",
	"LDU1m7TcU4JnlnaOxm3wV435FLGNiTIjYZ6nzzfDGBIg+9TOgBKCuT2IsbZPMFLZxNAQBrTLBJuACN9j",
	"yiBlaphPBeVaoQfKmFkfnk7tRQZncXaql6B8+4a/9nDsqztU12OQTpyxPOiYUf7SUkDDrgpNr2tEjU0f",
	"ajij/IsHJyjCpm2B5u8ZZjaEYJR/saubEU6k7c6o6JUkKhVcEZT7n+cWeXXZb1kfMORbwDnRuFLGqD84",
	"kVL4enzi3KXYEgK0zIJyU3P0EPOWbeJdapDLJPcHEEfHl5UX0dXlRbX3wgb3ZnjHRWBRdTTE3rFqpOPh",
	"Rh0MujOjbPKcryImsZ4TadNZuEBBjUV1vU76Wc9rVm6c7qXbVIs3j3KfsOx7sd2YVUDfT+sWXn0KA5Yr",
	"5yoaVoMNOCHPTwjasmQ7thJnZ/PpmJ/Nagb7tZZepKL/Z4ngNl9xXQ75gbFG3F1cD3WBtz0vlCcAb1z6",
	"Sm094OaZKwvrBdbeRvOnYpLDl9ccliRdl8lakMdO3lhPuyn+GTfj6zbhOwq/gKIGuWfqNXxCg+QP7hK8",
	"3C5LgWibN35hz8YSVn2A5m4NGG7pIl6OLGmRDdCZKvulqELD3uW43zu7Pe31z64uT0yQenXR+9Trn/U+",
	"QI7zhW0ZxN2LvSRKsOzFC5xmjCFF5D2NAB6SyjVbSUwQDzUCqDRvF8ut9xi1rdZ2h0GcaWx78Ev3q5b3",
	"vYMMDxby7CPmi3xpJfIZ/NIW22dq7VthXTT4BW1BNs0gV/ucKtiqBZpmPLJOYru7pExbEN9LW1qsxB5Y",
	"EpTxfG/ZAmW8iFG2u1UFRFtwUQRuQS5xsILE6OjjyfHV2cnx7eBq3Pv5BG1BxuPeGKABgWUAQjkiEAJV",
	"P8EAgmusJgiDJlVI/ZfG4vP22Vc2ZrktbmvMOjZo/SM0/HS/MWBy6lBjdZ0DoWoK1WOgkYtQZ1TpbzsF",
	"fBR/2EOgndklGVgl9Fiiecd4jTI4dkO7aFix+eXugUhwjSGHGLs2AmZI2V4CRwOsr6C8bh2+mWF6ruye",
	"r22VqCAoNWv1hQ4QpsG/1uLPQ/PWkXi2Q8AOW0fnQX1u/Eu4LTlu4E1vXnYM2dO4yH/asJRwSJoSSYrO",
	"1/IhLaqWUd7MZBMLsS3b8+fC69AcS5D0hc9d4LzpFRx90WhYTOajBs2BENQD8wUqaczm4vgi0Zv32eV5",
	"VSNIB6q7aGBOrAeqSFhmgm1XNGlkErxtDTFEGL5PSsyzBPOOJDi22a/KmVwXJC3aWXlU1rKkmDCSeOdc",
	"14/YvIvRQKqZ97MXcKE5bLKqsiTBctFgxYr7/Go0RheDMYrmmM+IbXKusK9F+2LK/ubyLHkuIVKLG2xT",
	"uRN5vqxlI3+CT1hMhdV/rnGkiway4DD/6f9FghtMJ41/zJM0+bcogjCAG9mHwZEbZU+9vG8WjixpqOVp",
	"55XUnpoFqBaqqDfsK9up3DhuyyEfRLxAW8ejD9th+SWHxpijOaYy/6hMTCIK9Z0EfzHgTKAELqbMCTTJ",
	"q3yX6jxd0tlcw6ETEW4rtE4i5/0xOnO/NqUgUsKVyGREIPXuXlY75/1xRRGDo+NLZAMWs+IgDO7z1txg",
	"r7v/t+4exKop4TilwWFw0N3tHkBlXM/BqxmNTwTfiSp5rxnRyyo+mMCRNMGKRsjohEwcLOb172GBcgNI",
	"d9/aaSRRFVGGwc/mP9nu7kE0P0A0/vtPUSw7lpkOTuntjOhOTvM2EvyecCg2/AQvkaPyF0tlZ35gn3zm",
	"/QZHKV4wgWNV3tWo0INzFFwKFKyMrw6NezOYN2U4Il3D6Zs3b96gn+EOATSOmt/uirsVd6U9KnclWtqj",
	"HyMbcP+kqjcQgORdpQ+1RmDFRYfiqgwQBSnX+v0qY2EO36UL8z+qhTF3nNSuUlCOrB4itVDmDA+hpxwv",
	"bOFVKEWNq4NhCUGK6syWhWywxyiesAVSKaNgKYrUF8TtEUjhIw/W97ZcA+kiu7GqOklYXZu92pEpe9pW",
	"98c25gFDOpO8ek/DLbMhaDO5ieAAfdW3CuAHiPcUjkhsIpqwkCh6mIvGIo2KfQ7+IeYcDXHG0K+UKy34",
	"5wAQX7Pzf+lWzINLV+naR8tCiDrdeu4+lzd9PgeH/tnuzMFgIA2Irh8Hh8HPRB+VVbAUS5yYaRU0wjSu",
	"RdRb8HvDfhkLInO4EFW9csIo3BM6d8jBFcTgKjDczkLu9pZtRKyuv7h5Apio9MxzOpsTpSv3IPJbAROi",
	"Hwjh6Pqxk1Deub/ZeuMY6swJNoqxDRt6/eh9VkCmIqmwihBViPyeYQYHtLRcuUC9ScP7ftFku2oS+49K",
	"d6Z2JxnO7xsA05ix4r5HZQ/gkpqoSqqYtCpoQHU1MWP0bvc9uhAa9aKIpNqAmC4aEYKuP47HQ/TR8ufh",
	"2NXpACNDw6EBDuY4g+clCHjs3AdVLAIVUvd9TO/tHaUXcNC5pq6ncKkzgnKaZEnzishr6aet7ObXS34M",
	"Xf0u277+jsI6gm/bxV7xRdJ3e/Uvkpq/t9++RVdX/WPbSoPtGSnhAj0kkexFnnybQv+SU4YXaIKjLzZS",
	"cPGJlc9jZ4pT2jF7LjGcvB0al/Veu2b3gSxdhkF4LaaLSChXe9eZ24ymGtPZBgLLr1VHx9oLtsazqm/c",
	"KKir0MScSqSBsyDDxcRs5pYkSkB9SSKaGotDIzHVD0ZTh1LEWaTtV03yTxO6D9Oe9ob9zl53t/MBK8Io",
	"J4Vs7ZNO+WT77dsuQrXefGMekjjQEmHGFNoqwWClSyPjWJsAl8TbXVB/WSWTcYNgDUyMwPUCpZfK3pDo",
	"xLbluU3sSxkK4xSX96JlmDcj4Vb7k0JC0hnlmKH+sLzLMa1vHFU5OmeLF29gN78RpspAlapch4sWmTLH",
	"YDwzVWhCDOwyQrWzYbS0R9AF9qjt3libyW8pvN4O5bN2aNop212/1UR8O1B0cZoYzwlIoWujye/f3Wy9",
	"cdEPYFXI+qptyCSBSys/WWO/leloXikiUQ8+dmoJhq+9u/XOw+U9Apkjr/k440KvsFVRrDr2zM6PwucM",
	"qtLkBAJ+kZmt+fKNgTLWaUM0vb+7m6dKCIcgupJ82/mXK/eWbL+8ocLmZJqfLIBP9gZhkIvm8I8W33+4",
	"OXdf99x9iZ8A8OvNIF87NAeAzzJTokEvoC28aS20x6pIJVto940sG11792/Q6WrJwKPQ8HVuwZh4MP6u",
	"0r5mk6aTyl34Q5v9mcgdl/2BPzNm7+D//bMtC0CbeYdRpT8H1XGM2r+u3+3uog7qc9vMDt8duNl6Y999",
	"t7vrfDK1z7ddxil/20vrnCpluG+jldjna9HK+fpUaElJzapJzlrHKZKf7E7G7J8bV/Fjuwprd+//N9jd",
	"e9RBV7wMWZd1/H2u41k5bKPnfxI9h29AQJHMZiNRJR2p8UzBZ5YBAQVhUDy7MWepikRKlC1nmQGHRasN",
	"FCkOJcGxHVmpiUAprFn02Clrj6tqH3YUCGmp/FEpdhQQ2RzA+f+dSb34AdnjwUQJRnTxcRN1iK7v927c",
	"xymJ2hFuwE61FtKxXHTu9+ytqVUp3eO8vrdJ7G4Su5vE7iaxu0nsbhK7m8TuJrG7SexuErubxO4Pldit",
	"XLDaJHg3Cd5NgneT4N0keDcJ3k2Cd6Pnf84ELyqyk1+d57WpUG+i115U34nz+047lVtaq3K82F618t3a",
	"Kr50Xr/C6EvAuktjm8zrJvO6ybxuMq/fJfP6PUJW76Xg9QPWTXC0CY5+hOBoA75fB3wvg7sS+CyBusJ3",
	"tNTkS6hWftliNVKbE8z0HEVzEn3Jv7SwPkYb5R9M2EC0DUTbQLQNRPtzQDT/57s2GG2D0TYYbYPRDEYr",
	"gM/LIJqhQ+R9DpPqX6swNt61Nl58wjtWHZzt3O8FTzdP/xUAAP//j2nJDRGPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
